# Generated by Django 3.0.2 on 2020-01-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_hospital_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='phone',
        ),
    ]
